version: '2'
services:
  frontend:
    build: ./frontend/
    ports:
      - "58080:8080"
    links:
      - "app"
  app:
    build: ./app/
    command: python app.py
    volumes:
      - ./app/sample:/app
    ports:
      - "15000:5000"
    expose:
      - "5000"
    links:
      - backend
  backend:
    build: ./backend
    command: redis-server
    volumes:
      - ./tmp/redis:/data
    expose:
      - "6379"
  tester:
    build: ./tester
    links:
      - backend
      - app
    volumes:
      - ./:/code
